// Code generated by goyacc - DO NOT EDIT.

package parse

import __yyfmt__ "fmt"

// import "strings"

// goyacc -l -o parser.go parser.y

type yySymType struct {
	yys    int
	result *Expr

	key, op, value string
}

type yyXError struct {
	state, xsym int
}

const (
	yyDefault = 57351
	yyEofCode = 57344
	EQ        = 57346
	NE        = 57347
	PROTO     = 57348
	TCP       = 57349
	UDP       = 57350
	yyErrCode = 57345

	yyMaxDepth = 200
	yyTabOfs   = -10
)

var (
	yyPrec = map[int]int{}

	yyXLAT = map[int]int{
		57344: 0,  // $end (8x)
		57346: 1,  // EQ (8x)
		57347: 2,  // NE (8x)
		57348: 3,  // PROTO (5x)
		57354: 4,  // key (3x)
		57355: 5,  // op (3x)
		57349: 6,  // TCP (3x)
		57350: 7,  // UDP (3x)
		57353: 8,  // expr (2x)
		57352: 9,  // Start (1x)
		57356: 10, // value (1x)
		57351: 11, // $default (0x)
		57345: 12, // error (0x)
	}

	yySymNames = []string{
		"$end",
		"EQ",
		"NE",
		"PROTO",
		"key",
		"op",
		"TCP",
		"UDP",
		"expr",
		"Start",
		"value",
		"$default",
		"error",
	}

	yyTokenLiteralStrings = map[int]string{
		57346: "=",
		57347: "!=",
		57348: "proto",
		57349: "tcp",
		57350: "udp",
	}

	yyReductions = map[int]struct{ xsym, components int }{
		0: {0, 1},
		1: {9, 1},
		2: {8, 3},
		3: {8, 3},
		4: {8, 3},
		5: {4, 1},
		6: {5, 1},
		7: {5, 1},
		8: {10, 1},
		9: {10, 1},
	}

	yyXErrors = map[yyXError]string{}

	yyParseTab = [14][]uint8{
		// 0
		{3: 14, 13, 8: 12, 11},
		{10},
		{9, 16, 17, 5: 22},
		{1: 16, 17, 5: 15},
		{5, 5, 5},
		// 5
		{3: 14, 19, 6: 20, 21, 10: 18},
		{3: 4, 6: 4, 4},
		{3: 3, 6: 3, 3},
		{7, 7, 7},
		{6, 6, 6},
		// 10
		{2, 2, 2},
		{1, 1, 1},
		{3: 14, 13, 8: 23},
		{8, 16, 17, 5: 22},
	}
)

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyLexerEx interface {
	yyLexer
	Reduced(rule, state int, lval *yySymType) bool
}

func yySymName(c int) (s string) {
	x, ok := yyXLAT[c]
	if ok {
		return yySymNames[x]
	}

	if c < 0x7f {
		return __yyfmt__.Sprintf("%q", c)
	}

	return __yyfmt__.Sprintf("%d", c)
}

func yylex1(yylex yyLexer, lval *yySymType) (n int) {
	n = yylex.Lex(lval)
	if n <= 0 {
		n = yyEofCode
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("\nlex %s(%#x %d), lval: %+v\n", yySymName(n), n, n, lval)
	}
	return n
}

func yyParse(yylex yyLexer) int {
	const yyError = 12

	yyEx, _ := yylex.(yyLexerEx)
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, 200)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yyerrok := func() {
		if yyDebug >= 2 {
			__yyfmt__.Printf("yyerrok()\n")
		}
		Errflag = 0
	}
	_ = yyerrok
	yystate := 0
	yychar := -1
	var yyxchar int
	var yyshift int
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	if yychar < 0 {
		yylval.yys = yystate
		yychar = yylex1(yylex, &yylval)
		var ok bool
		if yyxchar, ok = yyXLAT[yychar]; !ok {
			yyxchar = len(yySymNames) // > tab width
		}
	}
	if yyDebug >= 4 {
		var a []int
		for _, v := range yyS[:yyp+1] {
			a = append(a, v.yys)
		}
		__yyfmt__.Printf("state stack %v\n", a)
	}
	row := yyParseTab[yystate]
	yyn = 0
	if yyxchar < len(row) {
		if yyn = int(row[yyxchar]); yyn != 0 {
			yyn += yyTabOfs
		}
	}
	switch {
	case yyn > 0: // shift
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		yyshift = yyn
		if yyDebug >= 2 {
			__yyfmt__.Printf("shift, and goto state %d\n", yystate)
		}
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	case yyn < 0: // reduce
	case yystate == 1: // accept
		if yyDebug >= 2 {
			__yyfmt__.Println("accept")
		}
		goto ret0
	}

	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			if yyDebug >= 1 {
				__yyfmt__.Printf("no action for %s in state %d\n", yySymName(yychar), yystate)
			}
			msg, ok := yyXErrors[yyXError{yystate, yyxchar}]
			if !ok {
				msg, ok = yyXErrors[yyXError{yystate, -1}]
			}
			if !ok && yyshift != 0 {
				msg, ok = yyXErrors[yyXError{yyshift, yyxchar}]
			}
			if !ok {
				msg, ok = yyXErrors[yyXError{yyshift, -1}]
			}
			if yychar > 0 {
				ls := yyTokenLiteralStrings[yychar]
				if ls == "" {
					ls = yySymName(yychar)
				}
				if ls != "" {
					switch {
					case msg == "":
						msg = __yyfmt__.Sprintf("unexpected %s", ls)
					default:
						msg = __yyfmt__.Sprintf("unexpected %s, %s", ls, msg)
					}
				}
			}
			if msg == "" {
				msg = "syntax error"
			}
			yylex.Error(msg)
			Nerrs++
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				row := yyParseTab[yyS[yyp].yys]
				if yyError < len(row) {
					yyn = int(row[yyError]) + yyTabOfs
					if yyn > 0 { // hit
						if yyDebug >= 2 {
							__yyfmt__.Printf("error recovery found error shift in state %d\n", yyS[yyp].yys)
						}
						yystate = yyn /* simulate a shift of "error" */
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery failed\n")
			}
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yySymName(yychar))
			}
			if yychar == yyEofCode {
				goto ret1
			}

			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	r := -yyn
	x0 := yyReductions[r]
	x, n := x0.xsym, x0.components
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= n
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	exState := yystate
	yystate = int(yyParseTab[yyS[yyp].yys][x]) + yyTabOfs
	/* reduction by production r */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce using rule %v (%s), and goto state %d\n", r, yySymNames[x], yystate)
	}

	switch r {
	case 1:
		{
			yylex.(*bpfLex).setResult(yyS[yypt-0].result)
		}
	case 2:
		{
			yyVAL.result = &Expr{Op: yyS[yypt-1].op, Left: yyS[yypt-2].result, Right: yyS[yypt-0].result}
		}
	case 3:
		{
			yyVAL.result = &Expr{}
		}
	case 4:
		{
			yyVAL.result = &Expr{}
		}
	case 5:
		{
			yyVAL.key = yyS[yypt-0].key
		}
	case 6:
		{
			yyVAL.op = yyS[yypt-0].op
		}
	case 7:
		{
			yyVAL.op = yyS[yypt-0].op
		}
	case 8:
		{
			yyVAL.value = yyS[yypt-0].value
		}
	case 9:
		{
			yyVAL.value = yyS[yypt-0].value
		}

	}

	if yyEx != nil && yyEx.Reduced(r, exState, &yyVAL) {
		return -1
	}
	goto yystack /* stack new state and value */
}
