# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    name: unit-test
    runs-on: windows-latest
    env:
      CGO_ENABLED: 0 
    steps:

    - name: clone-repo
      uses: actions/checkout@v4

    - name: setup-go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: go-fmt
      run : gofmt -l -w .

    - name: go-vet
      run : go vet

    - name: go-test
      run : go test -v -timeout 120s -tags "-race" ./...  
